env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - https://converter.levsek.com.mx
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: https://converter.levsek.com.mx
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules:
  - action: INFO
    customMessage: ''
    id: 10109
  - action: INFO
    customMessage: ''
    id: 10015
  - action: INFO
    customMessage: ''
    id: 10049
  - action: INFO
    customMessage: ''
    id: 10055
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: web-report.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: web-report.json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
